### PR TITLE
Add all rhel platforms (from Ohai source)

### PR DESCRIPTION
**Pull request by carldjohnston**
Signed-off-by: Carl Johnston <carldjohnston@gmail.com>

### CODE REVIEW

**Comment by jmauro** [comment]
Hello again @carldjohnston,

Have tested the cookbook on all thoses platform? If that the case, shouldn't we also add those platform on the metadata file also?

Regards,
JM

**Comment by carldjohnston** [comment]
Hi @jmauro,

I haven't tested with all platforms - I haven't even heard of half of them!

Should the cookbook allow running on rhel platform families regardless of whether you've tested them (and list tested platforms in the readme)? 

I think that locking a cookbook to a only named platforms a bit restrictive.

Cheers,

Carl

**Comment by kamaradclimber** [comment]
@carldjohnston thanks for the patch!
Don't forget that `supports` metadata is only informative and not enforced at all.
We prefer to avoid adding platforms for which we don't have automated tests (even though it is likely that platforms similiar to centos/redhat will work)

**Comment by kamaradclimber** [comment]
If you use one of the platform you've added, I recommend that you create a wrapper cookbook to tweak the attribute to your will.

**Pull request closed without merging**
