### PR TITLE
Ubuntu

### PR DESCRIPTION
**Pull request by crashdummymch**
Added ubuntu support

### CODE REVIEW

**Comment by jmauro** [comment]
Hello @crashdummymch,

Thanks for the PR, and the add of the ubuntu support. As far as I can read, the resource you are creating for `ubuntu` is pretty much the same as the `rhel`, the only difference I see is the function `modload_file`, is that correct? Does this resource works fine on ubuntu? Have you tested it? Does it work on all ubuntu version?

If that is the case, maybe a unique resource should be created since 95% of the code is the same and we should take care of `modload_file` to handle `platform_version` properly, do think this could do the trick?

Regards,
JM

**Comment by crashdummymch** [comment]
I have tested with ubuntu 16.04. I do not have access to older versions.  I was going on the fact that it looked like you were naming the resources by platform family, which is why i created the new resource.  If you would like to handle this in current resource and move it to the function that is fine.

**Comment by jmauro** [comment]
hello @crashdummymch,
This idea behind the `rhel` resource was that I was not sure the code was fully functional on debian/ubuntu so I wanted to split clearly the resource. But according to you, the entire cookbook is functional on Debian platform so let's merge the common code :smile: 

Regards,
JM

**Comment by crashdummymch** [comment]
so i'm not sure what you are asking me to do in order for this pr to be accepted.  could you please be more specific?

**Comment by crashdummymch** [comment]
merged debian and rhel resource definitions per request

**Comment by nacc** [comment]
What's the status of these changes?

**Comment by jmauro** [comment]
Hello,

My bad, I'll look into it asap. 

Regards, 
JM

**Pull request merged**
