### PR TITLE
Add Oracle Linux since it is in the Red Hat family 

### PR DESCRIPTION
**Pull request by taharah**
* Oracle Linux is part of the Red Hat platform family, and thus, it the attributes should be automatically resolved the same as the other Red Hat distributions. 
* Resolves all Rubocop violations.

### CODE REVIEW

**Comment by jmauro** [comment]
Hello @taharah,

Thanks for the PR. 

Apparently Travis keys issue, let me fix this and rebase on it, sound good?

Regards,
JM

**Comment by jmauro** [comment]
@taharah could update the README to reflect the new supported OS?

**Comment by jmauro** [comment]
@taharah: done the travis tests are now working.

**Comment by taharah** [comment]
@jmauro I updated the README, but the Travis builds seem to be failing for the same reason still.

**Comment by jmauro** [comment]
@taharah could you do a `git rebase -p origin/master` ?

**Comment by taharah** [comment]
I rebased on master and it's still failing 😞

**Comment by jmauro** [comment]
Hello,

I don't understand, on my yesterday build I don't have any error: https://travis-ci.org/criteo-cookbooks/kernel-modules/builds/322272382

**Comment by taharah** [comment]
Looks like it's due to the following from the logs:

```
Encrypted environment variables have been removed for security reasons.
See https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions
```

**Comment by jmauro** [comment]
ok let me try something else...

**Comment by jmauro** [comment]
OK of course kitchen-dokken won't work for this kind of tests :D.

I tried to disable `kitchen-test`for external contributor, could test to see if it works (No matter you PR will be accepted since there is no major addition)

**Pull request merged**
