### PR TITLE
Include spaces between module name and option

### PR DESCRIPTION
**Pull request by carldjohnston**
Signed-off-by: Carl Johnston <carldjohnston@gmail.com>

### CODE REVIEW

**Comment by jmauro** [comment]
Hello @carldjohnston,

Thanks for the PR. This is a good catch. 
I know that the tests are failing for now (We will look at them right away), but would you mind adding some tests for catching that mistake?

Regards,
JM

**Comment by carldjohnston** [comment]
Hi @jmauro,

I'll try to add some tests - might need some help later on! :)

Cheers,

Carl

**Comment by kamaradclimber** [comment]
@jmauro tests are failing because travis secrets are not decrypted on PR coming from a fork (security measure).
@carldjohnston once you consider the PR as ready, ping @jmauro (or @criteo-cookbooks/sre-core team) and we'll run the test. You can probably launch the test locally with a vagrant kitchen driver or with your own ec2 credentials.

**Comment by jmauro** [comment]
@carldjohnston sorry, for the delay. Will look into it soon. Keep you poste de.

**Comment by jmauro** [comment]
Those changes have been integrated. Thanks @carldjohnston for the report.

Releasing today.

**Pull request closed without merging**
